---
image: docker:///cloudfoundry/warden-ci

paths:
  warden-linux: gopath/src/github.com/cloudfoundry-incubator/warden-linux

run:
  path: gopath/src/github.com/cloudfoundry-incubator/warden-linux/scripts/concourse-test
