// This file was generated by counterfeiter
package fake_copier

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/old/rootfs_provider"
)

type FakeCopier struct {
	CopyStub        func(src, dest string) error
	copyMutex       sync.RWMutex
	copyArgsForCall []struct {
		src  string
		dest string
	}
	copyReturns struct {
		result1 error
	}
}

func (fake *FakeCopier) Copy(src string, dest string) error {
	fake.copyMutex.Lock()
	fake.copyArgsForCall = append(fake.copyArgsForCall, struct {
		src  string
		dest string
	}{src, dest})
	fake.copyMutex.Unlock()
	if fake.CopyStub != nil {
		return fake.CopyStub(src, dest)
	} else {
		return fake.copyReturns.result1
	}
}

func (fake *FakeCopier) CopyCallCount() int {
	fake.copyMutex.RLock()
	defer fake.copyMutex.RUnlock()
	return len(fake.copyArgsForCall)
}

func (fake *FakeCopier) CopyArgsForCall(i int) (string, string) {
	fake.copyMutex.RLock()
	defer fake.copyMutex.RUnlock()
	return fake.copyArgsForCall[i].src, fake.copyArgsForCall[i].dest
}

func (fake *FakeCopier) CopyReturns(result1 error) {
	fake.CopyStub = nil
	fake.copyReturns = struct {
		result1 error
	}{result1}
}

var _ rootfs_provider.Copier = new(FakeCopier)
