// This file was generated by counterfeiter
package fake_rootfs_provider

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/rootfs_provider"
	"github.com/pivotal-golang/lager"
)

type FakeRootFSCleaner struct {
	CleanStub        func(logger lager.Logger, id string) error
	cleanMutex       sync.RWMutex
	cleanArgsForCall []struct {
		logger lager.Logger
		id     string
	}
	cleanReturns struct {
		result1 error
	}
}

func (fake *FakeRootFSCleaner) Clean(logger lager.Logger, id string) error {
	fake.cleanMutex.Lock()
	fake.cleanArgsForCall = append(fake.cleanArgsForCall, struct {
		logger lager.Logger
		id     string
	}{logger, id})
	fake.cleanMutex.Unlock()
	if fake.CleanStub != nil {
		return fake.CleanStub(logger, id)
	} else {
		return fake.cleanReturns.result1
	}
}

func (fake *FakeRootFSCleaner) CleanCallCount() int {
	fake.cleanMutex.RLock()
	defer fake.cleanMutex.RUnlock()
	return len(fake.cleanArgsForCall)
}

func (fake *FakeRootFSCleaner) CleanArgsForCall(i int) (lager.Logger, string) {
	fake.cleanMutex.RLock()
	defer fake.cleanMutex.RUnlock()
	return fake.cleanArgsForCall[i].logger, fake.cleanArgsForCall[i].id
}

func (fake *FakeRootFSCleaner) CleanReturns(result1 error) {
	fake.CleanStub = nil
	fake.cleanReturns = struct {
		result1 error
	}{result1}
}

var _ rootfs_provider.RootFSCleaner = new(FakeRootFSCleaner)
