// This file was generated by counterfeiter
package fake_rootfs_provider

import (
	"net/url"
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/old/rootfs_provider"
	"github.com/cloudfoundry-incubator/garden-linux/process"
	"github.com/pivotal-golang/lager"
)

type FakeRootFSProvider struct {
	ProvideRootFSStub        func(logger lager.Logger, id string, rootfs *url.URL, namespaced bool) (mountpoint string, envvar process.Env, err error)
	provideRootFSMutex       sync.RWMutex
	provideRootFSArgsForCall []struct {
		logger     lager.Logger
		id         string
		rootfs     *url.URL
		namespaced bool
	}
	provideRootFSReturns struct {
		result1 string
		result2 process.Env
		result3 error
	}
}

func (fake *FakeRootFSProvider) ProvideRootFS(logger lager.Logger, id string, rootfs *url.URL, namespaced bool) (mountpoint string, envvar process.Env, err error) {
	fake.provideRootFSMutex.Lock()
	fake.provideRootFSArgsForCall = append(fake.provideRootFSArgsForCall, struct {
		logger     lager.Logger
		id         string
		rootfs     *url.URL
		namespaced bool
	}{logger, id, rootfs, namespaced})
	fake.provideRootFSMutex.Unlock()
	if fake.ProvideRootFSStub != nil {
		return fake.ProvideRootFSStub(logger, id, rootfs, namespaced)
	} else {
		return fake.provideRootFSReturns.result1, fake.provideRootFSReturns.result2, fake.provideRootFSReturns.result3
	}
}

func (fake *FakeRootFSProvider) ProvideRootFSCallCount() int {
	fake.provideRootFSMutex.RLock()
	defer fake.provideRootFSMutex.RUnlock()
	return len(fake.provideRootFSArgsForCall)
}

func (fake *FakeRootFSProvider) ProvideRootFSArgsForCall(i int) (lager.Logger, string, *url.URL, bool) {
	fake.provideRootFSMutex.RLock()
	defer fake.provideRootFSMutex.RUnlock()
	return fake.provideRootFSArgsForCall[i].logger, fake.provideRootFSArgsForCall[i].id, fake.provideRootFSArgsForCall[i].rootfs, fake.provideRootFSArgsForCall[i].namespaced
}

func (fake *FakeRootFSProvider) ProvideRootFSReturns(result1 string, result2 process.Env, result3 error) {
	fake.ProvideRootFSStub = nil
	fake.provideRootFSReturns = struct {
		result1 string
		result2 process.Env
		result3 error
	}{result1, result2, result3}
}

var _ rootfs_provider.RootFSProvider = new(FakeRootFSProvider)
