// This file was generated by counterfeiter
package fake_network_statisticser

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden"
	"github.com/cloudfoundry-incubator/garden-linux/linux_container"
)

type FakeNetworkStatisticser struct {
	StatisticsStub        func() (stats garden.ContainerNetworkStat, err error)
	statisticsMutex       sync.RWMutex
	statisticsArgsForCall []struct{}
	statisticsReturns     struct {
		result1 garden.ContainerNetworkStat
		result2 error
	}
}

func (fake *FakeNetworkStatisticser) Statistics() (stats garden.ContainerNetworkStat, err error) {
	fake.statisticsMutex.Lock()
	fake.statisticsArgsForCall = append(fake.statisticsArgsForCall, struct{}{})
	fake.statisticsMutex.Unlock()
	if fake.StatisticsStub != nil {
		return fake.StatisticsStub()
	} else {
		return fake.statisticsReturns.result1, fake.statisticsReturns.result2
	}
}

func (fake *FakeNetworkStatisticser) StatisticsCallCount() int {
	fake.statisticsMutex.RLock()
	defer fake.statisticsMutex.RUnlock()
	return len(fake.statisticsArgsForCall)
}

func (fake *FakeNetworkStatisticser) StatisticsReturns(result1 garden.ContainerNetworkStat, result2 error) {
	fake.StatisticsStub = nil
	fake.statisticsReturns = struct {
		result1 garden.ContainerNetworkStat
		result2 error
	}{result1, result2}
}

var _ linux_container.NetworkStatisticser = new(FakeNetworkStatisticser)
