// This file was generated by counterfeiter
package fake_spawner

import (
	"os"
	"sync"

	"github.com/cloudfoundry-incubator/garden"
	"github.com/cloudfoundry-incubator/garden-linux/container_daemon"
)

type FakeSpawner struct {
	SpawnStub        func(spec garden.ProcessSpec) ([]*os.File, int, error)
	spawnMutex       sync.RWMutex
	spawnArgsForCall []struct {
		spec garden.ProcessSpec
	}
	spawnReturns struct {
		result1 []*os.File
		result2 int
		result3 error
	}
}

func (fake *FakeSpawner) Spawn(spec garden.ProcessSpec) ([]*os.File, int, error) {
	fake.spawnMutex.Lock()
	fake.spawnArgsForCall = append(fake.spawnArgsForCall, struct {
		spec garden.ProcessSpec
	}{spec})
	fake.spawnMutex.Unlock()
	if fake.SpawnStub != nil {
		return fake.SpawnStub(spec)
	} else {
		return fake.spawnReturns.result1, fake.spawnReturns.result2, fake.spawnReturns.result3
	}
}

func (fake *FakeSpawner) SpawnCallCount() int {
	fake.spawnMutex.RLock()
	defer fake.spawnMutex.RUnlock()
	return len(fake.spawnArgsForCall)
}

func (fake *FakeSpawner) SpawnArgsForCall(i int) garden.ProcessSpec {
	fake.spawnMutex.RLock()
	defer fake.spawnMutex.RUnlock()
	return fake.spawnArgsForCall[i].spec
}

func (fake *FakeSpawner) SpawnReturns(result1 []*os.File, result2 int, result3 error) {
	fake.SpawnStub = nil
	fake.spawnReturns = struct {
		result1 []*os.File
		result2 int
		result3 error
	}{result1, result2, result3}
}

var _ container_daemon.Spawner = new(FakeSpawner)
