// This file was generated by counterfeiter
package fake_rootfs_provider

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/resource_pool"
	"github.com/cloudfoundry-incubator/garden-shed/rootfs_provider"
	"github.com/pivotal-golang/lager"
)

type FakeRootFSProvider struct {
	CreateStub        func(log lager.Logger, id string, spec rootfs_provider.Spec) (mountpoint string, envvar []string, err error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		log  lager.Logger
		id   string
		spec rootfs_provider.Spec
	}
	createReturns struct {
		result1 string
		result2 []string
		result3 error
	}
	DestroyStub        func(log lager.Logger, id string) error
	destroyMutex       sync.RWMutex
	destroyArgsForCall []struct {
		log lager.Logger
		id  string
	}
	destroyReturns struct {
		result1 error
	}
}

func (fake *FakeRootFSProvider) Create(log lager.Logger, id string, spec rootfs_provider.Spec) (mountpoint string, envvar []string, err error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		log  lager.Logger
		id   string
		spec rootfs_provider.Spec
	}{log, id, spec})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(log, id, spec)
	} else {
		return fake.createReturns.result1, fake.createReturns.result2, fake.createReturns.result3
	}
}

func (fake *FakeRootFSProvider) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeRootFSProvider) CreateArgsForCall(i int) (lager.Logger, string, rootfs_provider.Spec) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].log, fake.createArgsForCall[i].id, fake.createArgsForCall[i].spec
}

func (fake *FakeRootFSProvider) CreateReturns(result1 string, result2 []string, result3 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 string
		result2 []string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeRootFSProvider) Destroy(log lager.Logger, id string) error {
	fake.destroyMutex.Lock()
	fake.destroyArgsForCall = append(fake.destroyArgsForCall, struct {
		log lager.Logger
		id  string
	}{log, id})
	fake.destroyMutex.Unlock()
	if fake.DestroyStub != nil {
		return fake.DestroyStub(log, id)
	} else {
		return fake.destroyReturns.result1
	}
}

func (fake *FakeRootFSProvider) DestroyCallCount() int {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return len(fake.destroyArgsForCall)
}

func (fake *FakeRootFSProvider) DestroyArgsForCall(i int) (lager.Logger, string) {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return fake.destroyArgsForCall[i].log, fake.destroyArgsForCall[i].id
}

func (fake *FakeRootFSProvider) DestroyReturns(result1 error) {
	fake.DestroyStub = nil
	fake.destroyReturns = struct {
		result1 error
	}{result1}
}

var _ resource_pool.RootFSProvider = new(FakeRootFSProvider)
