// This file was generated by counterfeiter
package fake_bridge_builder

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/container_pool"
)

type FakeBridgeBuilder struct {
	CreateStub        func(name string)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		name string
	}
	DestroyStub        func()
	destroyMutex       sync.RWMutex
	destroyArgsForCall []struct{}
}

func (fake *FakeBridgeBuilder) Create(name string) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		name string
	}{name})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		fake.CreateStub(name)
	}
}

func (fake *FakeBridgeBuilder) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeBridgeBuilder) CreateArgsForCall(i int) string {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].name
}

func (fake *FakeBridgeBuilder) Destroy() {
	fake.destroyMutex.Lock()
	fake.destroyArgsForCall = append(fake.destroyArgsForCall, struct{}{})
	fake.destroyMutex.Unlock()
	if fake.DestroyStub != nil {
		fake.DestroyStub()
	}
}

func (fake *FakeBridgeBuilder) DestroyCallCount() int {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return len(fake.destroyArgsForCall)
}

var _ container_pool.BridgeBuilder = new(FakeBridgeBuilder)
