// This file was generated by counterfeiter
package fake_rootfs_enterer

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/containerizer"
)

type FakeRootFSEnterer struct {
	EnterStub        func() error
	enterMutex       sync.RWMutex
	enterArgsForCall []struct{}
	enterReturns     struct {
		result1 error
	}
}

func (fake *FakeRootFSEnterer) Enter() error {
	fake.enterMutex.Lock()
	fake.enterArgsForCall = append(fake.enterArgsForCall, struct{}{})
	fake.enterMutex.Unlock()
	if fake.EnterStub != nil {
		return fake.EnterStub()
	} else {
		return fake.enterReturns.result1
	}
}

func (fake *FakeRootFSEnterer) EnterCallCount() int {
	fake.enterMutex.RLock()
	defer fake.enterMutex.RUnlock()
	return len(fake.enterArgsForCall)
}

func (fake *FakeRootFSEnterer) EnterReturns(result1 error) {
	fake.EnterStub = nil
	fake.enterReturns = struct {
		result1 error
	}{result1}
}

var _ containerizer.RootFSEnterer = new(FakeRootFSEnterer)
