// This file was generated by counterfeiter
package fake_rootfs_enterer

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/containerizer"
)

type FakeRootFSEnterer struct {
	EnterStub        func() error
	enterMutex       sync.RWMutex
	enterArgsForCall []struct{}
	enterReturns     struct {
		result1 error
	}
	UnmountOldRootFSStub        func() error
	unmountOldRootFSMutex       sync.RWMutex
	unmountOldRootFSArgsForCall []struct{}
	unmountOldRootFSReturns     struct {
		result1 error
	}
}

func (fake *FakeRootFSEnterer) Enter() error {
	fake.enterMutex.Lock()
	fake.enterArgsForCall = append(fake.enterArgsForCall, struct{}{})
	fake.enterMutex.Unlock()
	if fake.EnterStub != nil {
		return fake.EnterStub()
	} else {
		return fake.enterReturns.result1
	}
}

func (fake *FakeRootFSEnterer) EnterCallCount() int {
	fake.enterMutex.RLock()
	defer fake.enterMutex.RUnlock()
	return len(fake.enterArgsForCall)
}

func (fake *FakeRootFSEnterer) EnterReturns(result1 error) {
	fake.EnterStub = nil
	fake.enterReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRootFSEnterer) UnmountOldRootFS() error {
	fake.unmountOldRootFSMutex.Lock()
	fake.unmountOldRootFSArgsForCall = append(fake.unmountOldRootFSArgsForCall, struct{}{})
	fake.unmountOldRootFSMutex.Unlock()
	if fake.UnmountOldRootFSStub != nil {
		return fake.UnmountOldRootFSStub()
	} else {
		return fake.unmountOldRootFSReturns.result1
	}
}

func (fake *FakeRootFSEnterer) UnmountOldRootFSCallCount() int {
	fake.unmountOldRootFSMutex.RLock()
	defer fake.unmountOldRootFSMutex.RUnlock()
	return len(fake.unmountOldRootFSArgsForCall)
}

func (fake *FakeRootFSEnterer) UnmountOldRootFSReturns(result1 error) {
	fake.UnmountOldRootFSStub = nil
	fake.unmountOldRootFSReturns = struct {
		result1 error
	}{result1}
}

var _ containerizer.RootFSEnterer = new(FakeRootFSEnterer)
