// This file was generated by counterfeiter
package fake_term

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/container_daemon"
	"github.com/docker/docker/pkg/term"
)

type FakeTerm struct {
	GetWinsizeStub        func(fd uintptr) (*term.Winsize, error)
	getWinsizeMutex       sync.RWMutex
	getWinsizeArgsForCall []struct {
		fd uintptr
	}
	getWinsizeReturns struct {
		result1 *term.Winsize
		result2 error
	}
	SetWinsizeStub        func(fd uintptr, size *term.Winsize) error
	setWinsizeMutex       sync.RWMutex
	setWinsizeArgsForCall []struct {
		fd   uintptr
		size *term.Winsize
	}
	setWinsizeReturns struct {
		result1 error
	}
	SetRawTerminalStub        func(fd uintptr) (*term.State, error)
	setRawTerminalMutex       sync.RWMutex
	setRawTerminalArgsForCall []struct {
		fd uintptr
	}
	setRawTerminalReturns struct {
		result1 *term.State
		result2 error
	}
	RestoreTerminalStub        func(fd uintptr, state *term.State) error
	restoreTerminalMutex       sync.RWMutex
	restoreTerminalArgsForCall []struct {
		fd    uintptr
		state *term.State
	}
	restoreTerminalReturns struct {
		result1 error
	}
}

func (fake *FakeTerm) GetWinsize(fd uintptr) (*term.Winsize, error) {
	fake.getWinsizeMutex.Lock()
	fake.getWinsizeArgsForCall = append(fake.getWinsizeArgsForCall, struct {
		fd uintptr
	}{fd})
	fake.getWinsizeMutex.Unlock()
	if fake.GetWinsizeStub != nil {
		return fake.GetWinsizeStub(fd)
	} else {
		return fake.getWinsizeReturns.result1, fake.getWinsizeReturns.result2
	}
}

func (fake *FakeTerm) GetWinsizeCallCount() int {
	fake.getWinsizeMutex.RLock()
	defer fake.getWinsizeMutex.RUnlock()
	return len(fake.getWinsizeArgsForCall)
}

func (fake *FakeTerm) GetWinsizeArgsForCall(i int) uintptr {
	fake.getWinsizeMutex.RLock()
	defer fake.getWinsizeMutex.RUnlock()
	return fake.getWinsizeArgsForCall[i].fd
}

func (fake *FakeTerm) GetWinsizeReturns(result1 *term.Winsize, result2 error) {
	fake.GetWinsizeStub = nil
	fake.getWinsizeReturns = struct {
		result1 *term.Winsize
		result2 error
	}{result1, result2}
}

func (fake *FakeTerm) SetWinsize(fd uintptr, size *term.Winsize) error {
	fake.setWinsizeMutex.Lock()
	fake.setWinsizeArgsForCall = append(fake.setWinsizeArgsForCall, struct {
		fd   uintptr
		size *term.Winsize
	}{fd, size})
	fake.setWinsizeMutex.Unlock()
	if fake.SetWinsizeStub != nil {
		return fake.SetWinsizeStub(fd, size)
	} else {
		return fake.setWinsizeReturns.result1
	}
}

func (fake *FakeTerm) SetWinsizeCallCount() int {
	fake.setWinsizeMutex.RLock()
	defer fake.setWinsizeMutex.RUnlock()
	return len(fake.setWinsizeArgsForCall)
}

func (fake *FakeTerm) SetWinsizeArgsForCall(i int) (uintptr, *term.Winsize) {
	fake.setWinsizeMutex.RLock()
	defer fake.setWinsizeMutex.RUnlock()
	return fake.setWinsizeArgsForCall[i].fd, fake.setWinsizeArgsForCall[i].size
}

func (fake *FakeTerm) SetWinsizeReturns(result1 error) {
	fake.SetWinsizeStub = nil
	fake.setWinsizeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTerm) SetRawTerminal(fd uintptr) (*term.State, error) {
	fake.setRawTerminalMutex.Lock()
	fake.setRawTerminalArgsForCall = append(fake.setRawTerminalArgsForCall, struct {
		fd uintptr
	}{fd})
	fake.setRawTerminalMutex.Unlock()
	if fake.SetRawTerminalStub != nil {
		return fake.SetRawTerminalStub(fd)
	} else {
		return fake.setRawTerminalReturns.result1, fake.setRawTerminalReturns.result2
	}
}

func (fake *FakeTerm) SetRawTerminalCallCount() int {
	fake.setRawTerminalMutex.RLock()
	defer fake.setRawTerminalMutex.RUnlock()
	return len(fake.setRawTerminalArgsForCall)
}

func (fake *FakeTerm) SetRawTerminalArgsForCall(i int) uintptr {
	fake.setRawTerminalMutex.RLock()
	defer fake.setRawTerminalMutex.RUnlock()
	return fake.setRawTerminalArgsForCall[i].fd
}

func (fake *FakeTerm) SetRawTerminalReturns(result1 *term.State, result2 error) {
	fake.SetRawTerminalStub = nil
	fake.setRawTerminalReturns = struct {
		result1 *term.State
		result2 error
	}{result1, result2}
}

func (fake *FakeTerm) RestoreTerminal(fd uintptr, state *term.State) error {
	fake.restoreTerminalMutex.Lock()
	fake.restoreTerminalArgsForCall = append(fake.restoreTerminalArgsForCall, struct {
		fd    uintptr
		state *term.State
	}{fd, state})
	fake.restoreTerminalMutex.Unlock()
	if fake.RestoreTerminalStub != nil {
		return fake.RestoreTerminalStub(fd, state)
	} else {
		return fake.restoreTerminalReturns.result1
	}
}

func (fake *FakeTerm) RestoreTerminalCallCount() int {
	fake.restoreTerminalMutex.RLock()
	defer fake.restoreTerminalMutex.RUnlock()
	return len(fake.restoreTerminalArgsForCall)
}

func (fake *FakeTerm) RestoreTerminalArgsForCall(i int) (uintptr, *term.State) {
	fake.restoreTerminalMutex.RLock()
	defer fake.restoreTerminalMutex.RUnlock()
	return fake.restoreTerminalArgsForCall[i].fd, fake.restoreTerminalArgsForCall[i].state
}

func (fake *FakeTerm) RestoreTerminalReturns(result1 error) {
	fake.RestoreTerminalStub = nil
	fake.restoreTerminalReturns = struct {
		result1 error
	}{result1}
}

var _ container_daemon.Term = new(FakeTerm)
