// Code generated by protoc-gen-gogo.
// source: destroy_volume.proto
// DO NOT EDIT!

package garden

import proto "code.google.com/p/gogoprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type DestroyVolumeRequest struct {
	Handle           *string `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DestroyVolumeRequest) Reset()         { *m = DestroyVolumeRequest{} }
func (m *DestroyVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*DestroyVolumeRequest) ProtoMessage()    {}

func (m *DestroyVolumeRequest) GetHandle() string {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return ""
}

type DestroyVolumeResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DestroyVolumeResponse) Reset()         { *m = DestroyVolumeResponse{} }
func (m *DestroyVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*DestroyVolumeResponse) ProtoMessage()    {}

func init() {
}
