// Code generated by protoc-gen-gogo.
// source: unbind_volume.proto
// DO NOT EDIT!

package garden

import proto "code.google.com/p/gogoprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type UnbindVolumeRequest struct {
	ContainerHandle  *string `protobuf:"bytes,1,req,name=container_handle" json:"container_handle,omitempty"`
	VolumeHandle     *string `protobuf:"bytes,2,req,name=volume_handle" json:"volume_handle,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UnbindVolumeRequest) Reset()         { *m = UnbindVolumeRequest{} }
func (m *UnbindVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*UnbindVolumeRequest) ProtoMessage()    {}

func (m *UnbindVolumeRequest) GetContainerHandle() string {
	if m != nil && m.ContainerHandle != nil {
		return *m.ContainerHandle
	}
	return ""
}

func (m *UnbindVolumeRequest) GetVolumeHandle() string {
	if m != nil && m.VolumeHandle != nil {
		return *m.VolumeHandle
	}
	return ""
}

type UnbindVolumeResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnbindVolumeResponse) Reset()         { *m = UnbindVolumeResponse{} }
func (m *UnbindVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*UnbindVolumeResponse) ProtoMessage()    {}

func init() {
}
