// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/network/subnets"
)

type FakeBridgeNameGenerator struct {
	GenerateStub        func() string
	generateMutex       sync.RWMutex
	generateArgsForCall []struct{}
	generateReturns struct {
		result1 string
	}
}

func (fake *FakeBridgeNameGenerator) Generate() string {
	fake.generateMutex.Lock()
	fake.generateArgsForCall = append(fake.generateArgsForCall, struct{}{})
	fake.generateMutex.Unlock()
	if fake.GenerateStub != nil {
		return fake.GenerateStub()
	} else {
		return fake.generateReturns.result1
	}
}

func (fake *FakeBridgeNameGenerator) GenerateCallCount() int {
	fake.generateMutex.RLock()
	defer fake.generateMutex.RUnlock()
	return len(fake.generateArgsForCall)
}

func (fake *FakeBridgeNameGenerator) GenerateReturns(result1 string) {
	fake.GenerateStub = nil
	fake.generateReturns = struct {
		result1 string
	}{result1}
}

var _ subnets.BridgeNameGenerator = new(FakeBridgeNameGenerator)
