// This file was generated by counterfeiter
package fake_mapper

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/old/rootfs_provider"
)

type FakeMapper struct {
	MapStub        func(id int) int
	mapMutex       sync.RWMutex
	mapArgsForCall []struct {
		id int
	}
	mapReturns struct {
		result1 int
	}
}

func (fake *FakeMapper) Map(id int) int {
	fake.mapMutex.Lock()
	fake.mapArgsForCall = append(fake.mapArgsForCall, struct {
		id int
	}{id})
	fake.mapMutex.Unlock()
	if fake.MapStub != nil {
		return fake.MapStub(id)
	} else {
		return fake.mapReturns.result1
	}
}

func (fake *FakeMapper) MapCallCount() int {
	fake.mapMutex.RLock()
	defer fake.mapMutex.RUnlock()
	return len(fake.mapArgsForCall)
}

func (fake *FakeMapper) MapArgsForCall(i int) int {
	fake.mapMutex.RLock()
	defer fake.mapMutex.RUnlock()
	return fake.mapArgsForCall[i].id
}

func (fake *FakeMapper) MapReturns(result1 int) {
	fake.MapStub = nil
	fake.mapReturns = struct {
		result1 int
	}{result1}
}

var _ rootfs_provider.Mapper = new(FakeMapper)
