#!/usr/bin/env bash
set -e
set -x

if [ -z $GOPATH ]; then
  export GOROOT=/usr/local/go
  export GOPATH=$HOME/go
  export PATH=$GOROOT/bin:$PATH
  export PATH=$GOPATH/bin:$PATH
fi

go get github.com/awslabs/aws-sdk-go/aws
go get github.com/awslabs/aws-sdk-go/service/ec2

cd $(dirname $0)/..

go build -o scripts/awsreaper/awsreaper scripts/awsreaper/main.go

./scripts/awsreaper/awsreaper
