#!/bin/bash

set -e -x

export GARDEN_TEST_GRAPHPATH=/tmp/btrfs_mount
mkdir -p $GARDEN_TEST_GRAPHPATH

export GARDEN_TEST_ROOTFS=/opt/warden/rootfs

[ -d /opt/warden/nestable-rootfs ] && export GARDEN_NESTABLE_TEST_ROOTFS=/opt/warden/nestable-rootfs
[ -d /opt/warden/fuse-rootfs ] && export GARDEN_FUSE_TEST_ROOTFS=/opt/warden/fuse-rootfs
[ -d /opt/warden/docker-registry-rootfs ] && export GARDEN_DOCKER_REGISTRY_TEST_ROOTFS=/opt/warden/docker-registry-rootfs
[ -d /opt/warden/preexisting-users-rootfs ] && export GARDEN_PREEXISTING_USERS_TEST_ROOTFS=/opt/warden/preexisting-users-rootfs
[ -d /opt/warden/empty ] && export GARDEN_EMPTY_TEST_ROOTFS=/opt/warden/empty

export GODEPS_WORKSPACE=$PWD/Godeps/_workspace
export GOPATH=$GODEPS_WORKSPACE:$GOPATH
export PATH=$GODEPS_WORKSPACE/bin:$PATH

make

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p -race -cover -nodes=4 -seed=1436262803 "$@"

# don't leak coveralls token
set +x

if [ -n "$COVERALLS_TOKEN" ] && [ "$COVERALLS_TOKEN" != "{{coveralls_token}}" ] ; then
  go get github.com/dustin/goveralls

  profiles=$(find . -name '*.coverprofile' | grep -v fake | grep -v Godeps )

  echo mode: set > all.coverprofile
  cat $profiles | grep -v mode: >> all.coverprofile

  goveralls -service drone.io -coverprofile=all.coverprofile $COVERALLS_TOKEN || \
    echo "Coveralls failed. :("
fi
