#!/bin/bash

set -e -x

export GARDEN_TEST_ROOTFS=/opt/warden/rootfs
export GODEPS_WORKSPACE=$PWD/Godeps/_workspace

export GOPATH=$GODEPS_WORKSPACE:$GOPATH
export PATH=$GODEPS_WORKSPACE/bin:$PATH

make

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p -race -cover -skipMeasurements -keepGoing "$@"

# don't leak coveralls token
set +x

if [ -n "$COVERALLS_TOKEN" ] && [ "$COVERALLS_TOKEN" != "{{coveralls_token}}" ] ; then
  go get github.com/dustin/goveralls

  profiles=$(find . -name '*.coverprofile' | grep -v fake | grep -v Godeps )

  echo mode: set > all.coverprofile
  cat $profiles | grep -v mode: >> all.coverprofile

  goveralls -service drone.io -coverprofile=all.coverprofile $COVERALLS_TOKEN || \
    echo "Coveralls failed. :("
fi
