#!/bin/bash -l
# vim: set ft=sh

set -e

cd $(dirname $0)/..

go build -o out/garden

sudo ./out/garden \
  -depot=/opt/garden/containers \
  -bin=$PWD/linux_backend/bin \
  -rootfs=/opt/garden/rootfs \
  -snapshots=/opt/garden/snapshots \
  -overlays=/opt/garden/overlays \
  "$@"
