#!/bin/bash -l
# vim: set ft=sh

set -e

cd $(dirname $0)/..

go build -o out/warden

sudo ./out/warden \
  -depot=/opt/warden/containers \
  -bin=$PWD/linux_backend/bin \
  -rootfs=/opt/warden/rootfs \
  -snapshots=/opt/warden/snapshots \
  -overlays=/opt/warden/overlays \
  "$@"
