#!/bin/bash -l
# vim: set ft=sh

set -e

cd $(dirname $0)/..

go build -o out/garden

sudo ./out/garden \
  -depot=/opt/garden/containers \
  -bin=$PWD/linux_backend/bin \
  -rootfs=/opt/warden/rootfs \
  -graph=/opt/warden/graph \
  -snapshots=/opt/garden/snapshots \
  "$@"
