#!/bin/bash
# vim: set ft=sh

set -e -x

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`
export PATH=$FIRST_GOPATH/bin:$PATH

go get code.google.com/p/go.tools/cmd/cover
go get github.com/dustin/goveralls

WORKSPACE=$PWD/Godeps/_workspace

export GOPATH=$WORKSPACE:$GOPATH
export PATH=$WORKSPACE/bin:$PATH

mkdir -p /tmp/gobin
export GOBIN=/tmp/gobin
export PATH=$GOBIN:$PATH
go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p -race -cover -keepGoing -randomizeAllSpecs -slowSpecThreshold=15 "$@"

# don't leak coveralls token
set +x

if [ -n "$COVERALLS_TOKEN" ]; then
  profiles=$(find . -name '*.coverprofile' | grep -v fake)

  echo mode: set > all.coverprofile
  cat $profiles | grep -v mode: >> all.coverprofile

  goveralls -coverprofile=all.coverprofile $COVERALLS_TOKEN || \
    echo "Coveralls failed. :("
fi
