#!/usr/bin/env bash

set -e

ARGS=$@

if egrep -q integration <(echo "$ARGS"); then
   (cd ../../..; ./scripts/remote-fly ci/nested-garden-linux-tests.yml -- -nodes 4 $ARGS)
elif [ -d $ARGS ] && 
     [ "$(find $ARGS -maxdepth 1 -name '*_linux_test.go')" != "" ]; then
   (cd ../../..; ./scripts/remote-fly ci/nested-garden-linux-tests.yml $ARGS)
else
  ginkgo -r -race $ARGS
fi

