#!/usr/bin/env bash

set -e
set -x

repoPath=$(cd $(dirname $BASH_SOURCE)/.. && pwd)

if [ -z $GOPATH ]; then
  export GOPATH=$repoPath/Godeps/_workspace:$HOME/go
  export PATH=$GOPATH/bin:$PATH
fi

cd $repoPath

go build -o scripts/amimgr/amimgr scripts/amimgr/main.go

./scripts/amimgr/amimgr --commit `git rev-parse HEAD` \
                        --imageID `cat packer/garden-ci/AMI_IMAGE_ID`
