#!/usr/bin/env bash

set -e
set -x

repoPath=$(cd $(dirname $BASH_SOURCE)/.. && pwd)

if [ -z $GOROOT ]; then
  export GOROOT=/usr/local/go
  export PATH=$GOROOT/bin:$PATH
fi

if [ -z $GOPATH ]; then
  export GOPATH=$repoPath/Godeps/_workspace:$HOME/go
  export PATH=$GOPATH/bin:$PATH
fi

cd $repoPath

export BTRFS_SUPPORTED=true
go run scripts/amimgr/main.go --commit `git rev-parse HEAD` \
                        --imageID `cat packer/garden-ci/AMI_IMAGE_ID`
