#!/bin/bash
set -e -x -u

vagrant up

if [ $# -gt 1 ] && [ "$1" == "-u" ]; then
  shift 1
  vagrant ssh -c "cd /home/vagrant/go/src/github.com/cloudfoundry-incubator/garden-linux && sudo -E ./scripts/linux-unit-test $*"
else
  vagrant ssh -c "cd /home/vagrant/go/src/github.com/cloudfoundry-incubator/garden-linux && sudo -E ./scripts/prepare_btrfs.sh"
  vagrant ssh -c "cd /home/vagrant/go/src/github.com/cloudfoundry-incubator/garden-linux && sudo -E ./scripts/drone-test $*"
fi
