#!/usr/bin/env bash

set -e

ARGS=$@

if egrep -q integration <(echo "$ARGS"); then
  scripts/remote-fly -nodes 4 $ARGS
elif [ -d $ARGS ] && 
     [ "$(find $ARGS -maxdepth 1 -name '*_linux_test.go')" != "" ]; then
  scripts/test-in-docker $ARGS
else
  ginkgo -r -race $ARGS
fi

