#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/Godeps/_workspace:$GOPATH

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`

mkdir -p $FIRST_GOPATH/bin
export PATH=$FIRST_GOPATH/bin:$PATH

go get github.com/dustin/goveralls
go get github.com/onsi/ginkgo/ginkgo
go get code.google.com/p/go.tools/cmd/cover
go get -v -t ./...
ginkgo -cover -v -r -failOnPending -randomizeAllSpecs -race

# don't leak coveralls token
set +x

if [ -n "$COVERALLS_TOKEN" ]; then
  profiles=$(find . -name '*.coverprofile' | grep -v fake | grep -v Godeps | grep -v integration.coverprofile)

  echo mode: set > all.coverprofile
  cat $profiles | grep -v mode: >> all.coverprofile

  goveralls -service drone.io -coverprofile=all.coverprofile $COVERALLS_TOKEN || \
    echo "Coveralls failed. :("
fi
