// This file was generated by counterfeiter
package fake_container_daemon

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/containerizer"
)

type FakeContainerDaemon struct {
	StartStub        func() error
	startMutex       sync.RWMutex
	startArgsForCall []struct{}
	startReturns     struct {
		result1 error
	}
}

func (fake *FakeContainerDaemon) Start() error {
	fake.startMutex.Lock()
	fake.startArgsForCall = append(fake.startArgsForCall, struct{}{})
	fake.startMutex.Unlock()
	if fake.StartStub != nil {
		return fake.StartStub()
	} else {
		return fake.startReturns.result1
	}
}

func (fake *FakeContainerDaemon) StartCallCount() int {
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	return len(fake.startArgsForCall)
}

func (fake *FakeContainerDaemon) StartReturns(result1 error) {
	fake.StartStub = nil
	fake.startReturns = struct {
		result1 error
	}{result1}
}

var _ containerizer.ContainerDaemon = new(FakeContainerDaemon)
