// This file was generated by counterfeiter
package fake_subnet_pool

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/linux_backend"
	"github.com/cloudfoundry-incubator/garden-linux/network/subnets"
	"github.com/cloudfoundry-incubator/garden-linux/resource_pool"
	"github.com/pivotal-golang/lager"
)

type FakeSubnetPool struct {
	AcquireStub        func(subnet subnets.SubnetSelector, ip subnets.IPSelector, logger lager.Logger) (*linux_backend.Network, error)
	acquireMutex       sync.RWMutex
	acquireArgsForCall []struct {
		subnet subnets.SubnetSelector
		ip     subnets.IPSelector
		logger lager.Logger
	}
	acquireReturns struct {
		result1 *linux_backend.Network
		result2 error
	}
	ReleaseStub        func(network *linux_backend.Network, logger lager.Logger) error
	releaseMutex       sync.RWMutex
	releaseArgsForCall []struct {
		network *linux_backend.Network
		logger  lager.Logger
	}
	releaseReturns struct {
		result1 error
	}
	RemoveStub        func(network *linux_backend.Network, logger lager.Logger) error
	removeMutex       sync.RWMutex
	removeArgsForCall []struct {
		network *linux_backend.Network
		logger  lager.Logger
	}
	removeReturns struct {
		result1 error
	}
	CapacityStub        func() int
	capacityMutex       sync.RWMutex
	capacityArgsForCall []struct{}
	capacityReturns     struct {
		result1 int
	}
}

func (fake *FakeSubnetPool) Acquire(subnet subnets.SubnetSelector, ip subnets.IPSelector, logger lager.Logger) (*linux_backend.Network, error) {
	fake.acquireMutex.Lock()
	fake.acquireArgsForCall = append(fake.acquireArgsForCall, struct {
		subnet subnets.SubnetSelector
		ip     subnets.IPSelector
		logger lager.Logger
	}{subnet, ip, logger})
	fake.acquireMutex.Unlock()
	if fake.AcquireStub != nil {
		return fake.AcquireStub(subnet, ip, logger)
	} else {
		return fake.acquireReturns.result1, fake.acquireReturns.result2
	}
}

func (fake *FakeSubnetPool) AcquireCallCount() int {
	fake.acquireMutex.RLock()
	defer fake.acquireMutex.RUnlock()
	return len(fake.acquireArgsForCall)
}

func (fake *FakeSubnetPool) AcquireArgsForCall(i int) (subnets.SubnetSelector, subnets.IPSelector, lager.Logger) {
	fake.acquireMutex.RLock()
	defer fake.acquireMutex.RUnlock()
	return fake.acquireArgsForCall[i].subnet, fake.acquireArgsForCall[i].ip, fake.acquireArgsForCall[i].logger
}

func (fake *FakeSubnetPool) AcquireReturns(result1 *linux_backend.Network, result2 error) {
	fake.AcquireStub = nil
	fake.acquireReturns = struct {
		result1 *linux_backend.Network
		result2 error
	}{result1, result2}
}

func (fake *FakeSubnetPool) Release(network *linux_backend.Network, logger lager.Logger) error {
	fake.releaseMutex.Lock()
	fake.releaseArgsForCall = append(fake.releaseArgsForCall, struct {
		network *linux_backend.Network
		logger  lager.Logger
	}{network, logger})
	fake.releaseMutex.Unlock()
	if fake.ReleaseStub != nil {
		return fake.ReleaseStub(network, logger)
	} else {
		return fake.releaseReturns.result1
	}
}

func (fake *FakeSubnetPool) ReleaseCallCount() int {
	fake.releaseMutex.RLock()
	defer fake.releaseMutex.RUnlock()
	return len(fake.releaseArgsForCall)
}

func (fake *FakeSubnetPool) ReleaseArgsForCall(i int) (*linux_backend.Network, lager.Logger) {
	fake.releaseMutex.RLock()
	defer fake.releaseMutex.RUnlock()
	return fake.releaseArgsForCall[i].network, fake.releaseArgsForCall[i].logger
}

func (fake *FakeSubnetPool) ReleaseReturns(result1 error) {
	fake.ReleaseStub = nil
	fake.releaseReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubnetPool) Remove(network *linux_backend.Network, logger lager.Logger) error {
	fake.removeMutex.Lock()
	fake.removeArgsForCall = append(fake.removeArgsForCall, struct {
		network *linux_backend.Network
		logger  lager.Logger
	}{network, logger})
	fake.removeMutex.Unlock()
	if fake.RemoveStub != nil {
		return fake.RemoveStub(network, logger)
	} else {
		return fake.removeReturns.result1
	}
}

func (fake *FakeSubnetPool) RemoveCallCount() int {
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	return len(fake.removeArgsForCall)
}

func (fake *FakeSubnetPool) RemoveArgsForCall(i int) (*linux_backend.Network, lager.Logger) {
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	return fake.removeArgsForCall[i].network, fake.removeArgsForCall[i].logger
}

func (fake *FakeSubnetPool) RemoveReturns(result1 error) {
	fake.RemoveStub = nil
	fake.removeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSubnetPool) Capacity() int {
	fake.capacityMutex.Lock()
	fake.capacityArgsForCall = append(fake.capacityArgsForCall, struct{}{})
	fake.capacityMutex.Unlock()
	if fake.CapacityStub != nil {
		return fake.CapacityStub()
	} else {
		return fake.capacityReturns.result1
	}
}

func (fake *FakeSubnetPool) CapacityCallCount() int {
	fake.capacityMutex.RLock()
	defer fake.capacityMutex.RUnlock()
	return len(fake.capacityArgsForCall)
}

func (fake *FakeSubnetPool) CapacityReturns(result1 int) {
	fake.CapacityStub = nil
	fake.capacityReturns = struct {
		result1 int
	}{result1}
}

var _ resource_pool.SubnetPool = new(FakeSubnetPool)
